version: '3'

services:
  notes_service:
    build: ./
    command: ./notes_service
    environment:
      - CONFIG_PATH=${CONFIG_PATH}
    ports:
      - "8088:8088"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
