// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// NoteCreator is an autogenerated mock type for the NoteCreator type
type NoteCreator struct {
	mock.Mock
}

// CreateNote provides a mock function with given fields: ctx, title, content
func (_m *NoteCreator) CreateNote(ctx context.Context, title string, content string) (string, error) {
	ret := _m.Called(ctx, title, content)

	if len(ret) == 0 {
		panic("no return value specified for CreateNote")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(ctx, title, content)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, title, content)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, title, content)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewNoteCreator creates a new instance of NoteCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNoteCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *NoteCreator {
	mock := &NoteCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
