// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/crewblade/notes_service/internal/domain/models"
	mock "github.com/stretchr/testify/mock"
)

// NoteGetterById is an autogenerated mock type for the NoteGetterById type
type NoteGetterById struct {
	mock.Mock
}

// GetNoteById provides a mock function with given fields: ctx, id
func (_m *NoteGetterById) GetNoteById(ctx context.Context, id string) (models.Note, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetNoteById")
	}

	var r0 models.Note
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (models.Note, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) models.Note); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(models.Note)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewNoteGetterById creates a new instance of NoteGetterById. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNoteGetterById(t interface {
	mock.TestingT
	Cleanup(func())
}) *NoteGetterById {
	mock := &NoteGetterById{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
